package com.neilturner.aerialviews.providers.youtube

import java.util.Calendar
import java.util.ArrayDeque
import kotlin.random.Random
import timber.log.Timber

object QueryFormulaEngine {
    private const val TAG = "YouTubeQueries"

    enum class QueryCategory {
        AERIAL,
        NATURE,
    }

    enum class ContentCategory(
        val key: String,
        val queryCategory: QueryCategory,
    ) {
        NATURE("nature", QueryCategory.NATURE),
        ANIMALS("animals", QueryCategory.NATURE),
        DRONE("drone", QueryCategory.AERIAL),
        CITIES("cities", QueryCategory.NATURE),
        SPACE("space", QueryCategory.NATURE),
        OCEAN("ocean", QueryCategory.NATURE),
        WEATHER("weather", QueryCategory.NATURE),
        WINTER("winter", QueryCategory.NATURE),
    }

    data class CategoryPreferences(
        val categoryNature: Boolean = true,
        val categoryAnimals: Boolean = true,
        val categoryDrone: Boolean = true,
        val categoryCities: Boolean = true,
        val categorySpace: Boolean = true,
        val categoryOcean: Boolean = true,
        val categoryWeather: Boolean = true,
        val categoryWinter: Boolean = true,
    ) {
        fun isEnabled(category: ContentCategory): Boolean =
            when (category) {
                ContentCategory.NATURE -> categoryNature
                ContentCategory.ANIMALS -> categoryAnimals
                ContentCategory.DRONE -> categoryDrone
                ContentCategory.CITIES -> categoryCities
                ContentCategory.SPACE -> categorySpace
                ContentCategory.OCEAN -> categoryOcean
                ContentCategory.WEATHER -> categoryWeather
                ContentCategory.WINTER -> categoryWinter
            }
    }

    data class CategoryQuery(
        val category: ContentCategory,
        val query: String,
    )

    private data class CategoryConfig(
        val queryCategory: QueryCategory,
        val queries: List<String>,
        val titleKeywords: Set<String>,
        val preferredTitleKeywords: Set<String> = emptySet(),
        val uploaderKeywords: Set<String> = emptySet(),
    )

    val aiVideoBlacklist =
        listOf(
            "ai generated",
            "made with ai",
            "generated by ai",
            "created with ai",
            "rendered by ai",
            "sora",
            "runway ml",
            "runway",
            "stable diffusion",
            "midjourney video",
            "pika labs",
            "kling ai",
            "ai nature",
            "ai cinematic",
            "ai animation",
            "ai short film",
            "artificial intelligence video",
            "synthetically generated",
            "ai art video",
            "neural network video",
            "rendered with ai",
            "cgi",
            "cg animation",
            "3d animation",
            "3d render",
            "rendered",
            "procedural",
            "unreal engine",
            "blender render",
            "virtual scenery",
            "fantasy landscape",
            "dreamscape",
        )

    val bumperTitleBlacklist =
        listOf(
            "subscribe",
            "click here",
            "watch more",
            "full video",
            "part 1",
            "part 2",
            "episode",
            "compilation",
            "best of",
            "top 10",
            "reaction",
            "review",
            "unboxing",
            "vlog",
            "travel vlog",
            "travel diary",
            "travel guide",
            "travel film",
            "travel movie",
            "travel cinematic",
            "talking",
            "hosted by",
            "presented by",
            "tour guide",
            "city tour",
            "hotel",
            "resort",
            "things to do",
            "itinerary",
            "road trip",
            "backpacking",
            "backpacker",
            "honeymoon",
            "vacation",
            "vacay",
            "tutorial",
            "how to",
            "cooking",
            "gaming",
            "challenge",
            "prank",
            "storytime",
            "day in my life",
            "grwm",
            "get ready with me",
            "haul",
            "mukbang",
            "wallpaper",
            "background video",
            "animated",
            "animation",
            "cgi",
            "3d",
            "render",
            "rendered",
            "loop",
        )

    val qualitySignals =
        listOf(
            "no music",
            "no talking",
            "slow motion",
            "8k",
            "4k hdr",
            "cinematic",
            "timelapse",
            "real footage",
            "documentary",
            "nature film",
            "wildlife",
        )

    private val categoryConfigs =
        linkedMapOf(
            ContentCategory.NATURE to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    queries =
                        listOf(
                            "4k forest trail real footage no talking",
                            "4k mountain valley landscape timelapse",
                            "4k river gorge landscape no music",
                            "4k national park landscape documentary",
                            "4k waterfall forest real footage",
                            "4k canyon landscape nature film",
                            "4k countryside meadow landscape 4k",
                            "4k alpine valley landscape no talking",
                            "4k jungle rainforest ambient",
                            "4k mangrove forest river",
                            "4k desert landscape sunset",
                            "4k volcanic landscape iceland",
                            "4k canyon landscape usa",
                            "4k rice terrace asia landscape",
                            "4k cherry blossom japan ambient",
                            "4k autumn fall foliage timelapse",
                            "4k lavender field france scenic",
                            "4k vineyard landscape timelapse",
                            "4k glacier landscape timelapse",
                            "4k hot spring yellowstone",
                        ),
                    titleKeywords =
                        setOf(
                            "forest",
                            "mountain",
                            "landscape",
                            "river",
                            "waterfall",
                            "valley",
                            "canyon",
                            "meadow",
                            "countryside",
                            "national park",
                            "trail",
                            "alpine",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "real footage",
                            "documentary",
                            "nature film",
                            "national park",
                        ),
                ),
            ContentCategory.ANIMALS to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    queries =
                        listOf(
                            "4k wildlife documentary no talking",
                            "4k safari wildlife real footage",
                            "4k birds wildlife documentary 4k",
                            "4k whale documentary real footage",
                            "4k elephant wildlife documentary",
                            "4k deer forest wildlife footage",
                            "4k marine wildlife documentary 4k",
                            "4k national geographic wildlife 4k",
                            "4k savanna wildlife timelapse",
                            "4k tundra arctic wildlife",
                            "4k wetlands birds wildlife",
                            "4k grassland plains wildlife",
                            "4k arctic fox wildlife documentary",
                            "4k rainforest wildlife birds monkeys",
                            "4k mountain goats alpine wildlife",
                            "4k dolphins whales ocean wildlife",
                            "4k lion pride savanna wildlife",
                            "4k polar bear arctic documentary",
                            "4k jungle wildlife real footage no talking",
                            "4k birds of paradise rainforest documentary",
                        ),
                    titleKeywords =
                        setOf(
                            "wildlife",
                            "animal",
                            "animals",
                            "safari",
                            "bird",
                            "birds",
                            "whale",
                            "elephant",
                            "deer",
                            "lion",
                            "tiger",
                            "penguin",
                            "dolphin",
                            "marine life",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "documentary",
                            "national geographic",
                            "nat geo",
                            "real footage",
                        ),
                    uploaderKeywords = setOf("nat geo", "national geographic", "bbc earth", "discovery"),
                ),
            ContentCategory.DRONE to
                CategoryConfig(
                    queryCategory = QueryCategory.AERIAL,
                    queries =
                        listOf(
                            "4k drone aerial landscape no music",
                            "4k aerial nature cinematic no talking",
                            "4k drone flyover mountains 4k",
                            "4k fpv drone landscape real footage",
                            "4k aerial coastline cinematic no music",
                            "4k drone fjord cinematic real footage",
                            "4k aerial waterfall drone 4k",
                            "4k bird's eye landscape drone footage",
                            "4k estuary river delta aerial",
                            "4k drone norway fjords aerial no music",
                            "4k drone iceland waterfalls aerial footage",
                            "4k drone swiss alps flyover cinematic",
                            "4k drone desert dunes aerial timelapse",
                            "4k drone rice terraces bali aerial",
                            "4k drone autumn forest aerial 4k",
                            "4k drone winter mountains aerial no talking",
                            "4k drone coastline cliffs aerial cinematic",
                            "4k fpv canyon flythrough real footage",
                        ),
                    titleKeywords =
                        setOf(
                            "drone",
                            "aerial",
                            "flyover",
                            "flythrough",
                            "fpv",
                            "bird's eye",
                            "uav",
                            "cinematic aerial",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "drone",
                            "aerial",
                            "fpv",
                            "bird's eye",
                            "real footage",
                        ),
                ),
            ContentCategory.OCEAN to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    queries =
                        listOf(
                            "4k ocean waves real footage no music",
                            "4k underwater coral reef documentary",
                            "4k sea cliffs coastline waves 4k",
                            "4k beach waves real footage ambient",
                            "4k deep ocean documentary 4k",
                            "4k underwater marine life 4k",
                            "4k coral reef underwater real footage",
                            "4k coast waves sunset real footage",
                            "4k tropical beach ambient",
                            "4k mediterranean coast scenic",
                            "4k sea cliff coastal waves",
                            "4k arctic ocean icebergs documentary",
                            "4k pacific ocean sunset waves no music",
                            "4k atlantic coastline storm waves 4k",
                            "4k underwater kelp forest marine life",
                            "4k tropical lagoon clear water aerial",
                            "4k island coastline drone ocean 4k",
                            "4k sea caves coastal waves ambient",
                            "4k tide pools marine life documentary",
                            "4k fjord ocean inlet scenic footage",
                        ),
                    titleKeywords =
                        setOf(
                            "ocean",
                            "sea",
                            "underwater",
                            "beach",
                            "waves",
                            "reef",
                            "coral",
                            "coast",
                            "coastal",
                            "marine",
                            "sea cliffs",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "underwater",
                            "coral reef",
                            "marine life",
                            "real footage",
                            "documentary",
                        ),
                ),
            ContentCategory.SPACE to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    queries =
                        listOf(
                            "4k earth from space nasa timelapse",
                            "4k iss earth view real footage",
                            "4k milky way night sky timelapse",
                            "4k aurora borealis real timelapse",
                            "4k northern lights timelapse no music",
                            "4k nasa earth horizon space station",
                            "4k moonrise night sky real footage",
                            "4k stars night sky timelapse 4k",
                            "4k earth timelapse from iss no music",
                            "4k moon surface orbit footage",
                            "4k deep space nebula timelapse",
                            "4k star trails night sky desert",
                            "4k aurora iceland night sky timelapse",
                            "4k milky way over mountains real footage",
                            "4k satellite earth cloud patterns",
                            "4k northern lights norway real footage",
                            "4k aurora alaska winter sky",
                        ),
                    titleKeywords =
                        setOf(
                            "space",
                            "earth from space",
                            "iss",
                            "nasa",
                            "aurora",
                            "northern lights",
                            "milky way",
                            "night sky",
                            "stars",
                            "moonrise",
                            "space station",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "nasa",
                            "iss",
                            "earth from space",
                            "milky way",
                            "aurora",
                            "northern lights",
                        ),
                    uploaderKeywords = setOf("nasa", "esa"),
                ),
            ContentCategory.CITIES to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    queries =
                        listOf(
                            "4k city skyline timelapse no music",
                            "4k downtown skyline blue hour timelapse",
                            "4k city lights night timelapse 4k",
                            "4k urban architecture no talking",
                            "4k modern city skyline real footage",
                            "4k metropolis night skyline 4k",
                            "4k urban street architecture timelapse",
                            "4k rooftop skyline sunset city 4k",
                            "4k tokyo skyline night timelapse",
                            "4k new york skyline sunset timelapse",
                            "4k dubai skyline aerial cityscape",
                            "4k paris city lights timelapse",
                            "4k london architecture skyline 4k",
                            "4k singapore marina skyline night",
                            "4k hong kong harbor skyline timelapse",
                            "4k urban skyline rain night 4k",
                            "4k chicago skyline lakefront timelapse",
                        ),
                    titleKeywords =
                        setOf(
                            "city",
                            "urban",
                            "skyline",
                            "downtown",
                            "architecture",
                            "cityscape",
                            "metropolis",
                            "streets",
                            "street",
                            "rooftop",
                            "city lights",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "city skyline",
                            "urban",
                            "downtown",
                            "architecture",
                            "city lights",
                            "cityscape",
                        ),
                ),
            ContentCategory.WEATHER to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    queries =
                        listOf(
                            "4k thunderstorm landscape timelapse",
                            "4k storm clouds timelapse real footage",
                            "4k lightning storm real footage",
                            "4k rain over mountains timelapse",
                            "4k fog rolling through valley 4k",
                            "4k misty forest weather timelapse",
                            "4k storm front clouds 4k timelapse",
                            "4k heavy rain landscape real footage",
                            "4k monsoon rain forest ambience",
                            "4k blizzard snow storm landscape",
                            "4k dramatic clouds over ocean timelapse",
                            "4k sunrise fog valley timelapse",
                            "4k lightning over city skyline",
                            "4k desert dust storm timelapse",
                            "4k rainbow after storm landscape",
                            "4k hurricane ocean clouds timelapse",
                            "4k rolling thunderstorm plains timelapse",
                        ),
                    titleKeywords =
                        setOf(
                            "storm",
                            "thunderstorm",
                            "lightning",
                            "rain",
                            "cloud",
                            "clouds",
                            "fog",
                            "mist",
                            "storm front",
                            "weather",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "thunderstorm",
                            "lightning",
                            "storm clouds",
                            "real footage",
                        ),
                ),
            ContentCategory.WINTER to
                CategoryConfig(
                    queryCategory = QueryCategory.NATURE,
                    queries =
                        listOf(
                            "4k winter forest snow landscape",
                            "4k arctic landscape timelapse no music",
                            "4k frozen lake winter real footage",
                            "4k snowfall landscape 4k",
                            "4k glacier winter documentary",
                            "4k polar snow landscape no talking",
                            "4k snowy mountain valley 4k",
                            "4k ice landscape arctic real footage",
                            "4k snow covered pine forest no music",
                            "4k iceland winter landscape documentary",
                            "4k frozen waterfall winter 4k",
                            "4k snowy tundra ambient footage",
                            "4k alpine village winter snow",
                            "4k northern forest snowfall timelapse",
                            "4k sea ice arctic landscape",
                            "4k winter sunrise mountains timelapse",
                            "4k blizzard mountain pass real footage",
                        ),
                    titleKeywords =
                        setOf(
                            "winter",
                            "snow",
                            "snowfall",
                            "arctic",
                            "frozen",
                            "ice",
                            "glacier",
                            "polar",
                            "snowy",
                        ),
                    preferredTitleKeywords =
                        setOf(
                            "winter",
                            "arctic",
                            "glacier",
                            "polar",
                            "real footage",
                        ),
                ),
        )

    fun generateQueryPool(count: Int = 25): List<String> =
        generateQueryPool(
            count = count,
            prefs = CategoryPreferences(),
            entropySeed = refreshSeed(),
        )

    fun generateQueryPool(
        baseQuery: String,
        count: Int = 25,
        entropySeed: Long = 0L,
        prefs: CategoryPreferences = CategoryPreferences(),
    ): List<String> {
        val categoryPool = generateQueryPool(count = count, prefs = prefs, entropySeed = entropySeed)
        val normalizedBaseQuery = baseQuery.trim()
        if (normalizedBaseQuery.isBlank()) {
            return categoryPool
        }

        return (
            listOf(normalizedBaseQuery) +
                categoryPool +
                listOf("$normalizedBaseQuery 4k", "$normalizedBaseQuery cinematic")
        ).distinct()
            .shuffled(Random(entropySeed xor dailySeed() xor refreshSeed()))
            .take(count)
    }

    fun generateQueryPool(
        count: Int,
        prefs: CategoryPreferences,
        entropySeed: Long = 0L,
    ): List<String> {
        val enabledPools =
            categoryConfigs
                .filterKeys(prefs::isEnabled)
                .ifEmpty { defaultPools() }

        val selectedQueries =
            roundRobinQueries(
                pools = enabledPools.mapValues { (category, queries) ->
                    queries.queries
                        .shuffled(seedForCategory(category, entropySeed))
                        .toCollection(ArrayDeque())
                },
                count = count,
            )

        val expandedQueries = expandQueriesForNarrowCategorySelection(selectedQueries, count)
        val finalPool = expandedQueries.ifEmpty { SAFE_FALLBACK_QUERIES.take(count) }
        Timber.tag(TAG).d("Generated %s YouTube search variants across %s categories", finalPool.size, enabledPools.size)
        return finalPool
    }

    fun generateFallbackQueryPool(
        baseQuery: String,
        count: Int = 12,
        entropySeed: Long = 0L,
        prefs: CategoryPreferences = CategoryPreferences(),
    ): List<String> {
        val enabledQueries =
            generateQueryPool(
                count = (count * 3).coerceAtLeast(18),
                prefs = prefs,
                entropySeed = entropySeed xor 0x51A8C27L,
            )

        val fallbackQueries =
            if (enabledQueries.isNotEmpty()) {
                enabledQueries
            } else {
                buildSafeFallbackQueries(baseQuery)
            }

        return fallbackQueries
            .distinct()
            .shuffled(Random(entropySeed xor weeklySeed() xor refreshSeed()))
            .take(count)
    }

    fun categoryOf(query: String): QueryCategory =
        categoryForQuery(query)?.queryCategory
            ?: if (AERIAL_QUERY_REGEX.containsMatchIn(query)) {
                QueryCategory.AERIAL
            } else {
                QueryCategory.NATURE
            }

    fun categoryForQuery(query: String): ContentCategory? {
        val normalizedQuery = query.trim().lowercase()
        if (normalizedQuery.isBlank()) {
            return null
        }

        categoryConfigs.entries.firstOrNull { (_, config) ->
            config.queries.any { configuredQuery ->
                normalizedQuery == configuredQuery.lowercase()
            }
        }?.key?.let { return it }

        // Most generated variants append suffixes to base queries; map by prefix to keep category ownership.
        categoryConfigs.entries.firstOrNull { (_, config) ->
            config.queries.any { configuredQuery ->
                val normalizedConfigured = configuredQuery.lowercase()
                normalizedQuery.startsWith("$normalizedConfigured ")
            }
        }?.key?.let { return it }

        val inferredByKeywords =
            categoryConfigs.entries
                .map { (category, config) ->
                    val titleMatches = config.titleKeywords.count { keyword -> normalizedQuery.contains(keyword.lowercase()) }
                    val preferredMatches = config.preferredTitleKeywords.count { keyword -> normalizedQuery.contains(keyword.lowercase()) }
                    val uploaderMatches = config.uploaderKeywords.count { keyword -> normalizedQuery.contains(keyword.lowercase()) }
                    category to (titleMatches + preferredMatches * 2 + uploaderMatches * 2)
                }.maxByOrNull { (_, score) -> score }
                ?.takeIf { (_, score) -> score > 0 }
                ?.first

        return inferredByKeywords
    }

    fun enabledCategories(prefs: CategoryPreferences): List<ContentCategory> =
        ContentCategory.entries.filter(prefs::isEnabled).ifEmpty { defaultPools().keys.toList() }

    fun matchesCandidateCategory(
        title: String,
        uploader: String,
        category: ContentCategory?,
    ): Boolean {
        if (category == null) {
            return true
        }

        val config = categoryConfigs.getValue(category)
        val titleLower = title.lowercase()
        val uploaderLower = uploader.lowercase()

        val directMatch = config.titleKeywords.any(titleLower::contains)
        val uploaderMatch =
            config.uploaderKeywords.isNotEmpty() &&
                config.uploaderKeywords.any(uploaderLower::contains)
        val strongTitleMatch = config.preferredTitleKeywords.any(titleLower::contains)
        return directMatch || strongTitleMatch || uploaderMatch
    }

    fun categoryMatchScore(
        title: String,
        uploader: String,
        category: ContentCategory?,
    ): Int {
        if (category == null) {
            return 0
        }

        val config = categoryConfigs.getValue(category)
        val titleLower = title.lowercase()
        val uploaderLower = uploader.lowercase()
        val titleMatches = config.titleKeywords.count(titleLower::contains)
        val preferredMatches = config.preferredTitleKeywords.count(titleLower::contains)
        val uploaderMatches = config.uploaderKeywords.count(uploaderLower::contains)

        return titleMatches + preferredMatches * 2 + uploaderMatches * 2
    }

    fun totalPossibleCombinations(): Long =
        categoryConfigs.values.sumOf { config -> config.queries.size.toLong() }

    fun freshnessSeed(baseQuery: String): String =
        "${baseQuery.trim()}|${weeklySeed()}|${dailySeed()}|${refreshSeed()}|${timeBucket()}"

    fun categorySignature(prefs: CategoryPreferences): String =
        ContentCategory.entries.joinToString(separator = ",") { category ->
            if (prefs.isEnabled(category)) category.key else "-${category.key}"
        }

    private fun defaultPools(): Map<ContentCategory, CategoryConfig> =
        linkedMapOf(
            ContentCategory.NATURE to categoryConfigs.getValue(ContentCategory.NATURE),
            ContentCategory.OCEAN to categoryConfigs.getValue(ContentCategory.OCEAN),
            ContentCategory.DRONE to categoryConfigs.getValue(ContentCategory.DRONE),
        )

    private fun roundRobinQueries(
        pools: Map<ContentCategory, ArrayDeque<String>>,
        count: Int,
    ): List<String> {
        val selected = mutableListOf<String>()
        val buckets = pools.toMutableMap()

        while (selected.size < count && buckets.isNotEmpty()) {
            val exhausted = mutableListOf<ContentCategory>()

            ContentCategory.entries.forEach { category ->
                val bucket = buckets[category] ?: return@forEach
                val query = bucket.pollFirst()
                if (query != null) {
                    selected += query
                }
                if (bucket.isEmpty()) {
                    exhausted += category
                }
                if (selected.size >= count) {
                    return@forEach
                }
            }

            exhausted.forEach(buckets::remove)
        }

        return selected.distinct().take(count)
    }

    private fun expandQueriesForNarrowCategorySelection(
        baseQueries: List<String>,
        count: Int,
    ): List<String> {
        if (baseQueries.isEmpty()) {
            return emptyList()
        }
        if (baseQueries.size >= count) {
            return baseQueries.take(count)
        }

        val expandedQueries = LinkedHashSet(baseQueries)

        QUERY_VARIATION_SUFFIXES.forEach { suffix ->
            baseQueries.forEach { query ->
                val suffixToken = suffix.trim()
                if (query.contains(suffixToken, ignoreCase = true)) {
                    return@forEach
                }

                expandedQueries += "$query $suffixToken"
                if (expandedQueries.size >= count) {
                    return expandedQueries.take(count)
                }
            }
        }

        return expandedQueries.take(count)
    }

    private fun seedForCategory(
        category: ContentCategory,
        entropySeed: Long,
    ): Random =
        when (category) {
            ContentCategory.DRONE -> Random(refreshSeed() xor entropySeed xor category.ordinal.toLong())
            ContentCategory.CITIES,
            ContentCategory.SPACE,
            -> Random(weeklySeed() xor entropySeed xor category.ordinal.toLong())

            else -> Random(dailySeed() xor entropySeed xor category.ordinal.toLong())
        }

    private fun weeklySeed(): Long {
        val calendar = Calendar.getInstance()
        return calendar.get(Calendar.YEAR).toLong() * 1000 + calendar.get(Calendar.WEEK_OF_YEAR)
    }

    private fun dailySeed(): Long {
        val calendar = Calendar.getInstance()
        return calendar.get(Calendar.YEAR).toLong() * 10_000L + calendar.get(Calendar.DAY_OF_YEAR)
    }

    private fun refreshSeed(): Long = System.currentTimeMillis() / (1000L * 60L * 60L * 6L)

    private fun timeBucket(): String =
        when (Calendar.getInstance().get(Calendar.HOUR_OF_DAY)) {
            in 5..9 -> "morning"
            in 10..16 -> "day"
            in 17..20 -> "evening"
            else -> "night"
        }

    private val SAFE_FALLBACK_QUERIES =
        listOf(
            "4k national park landscape documentary",
            "4k ocean waves real footage no music",
            "4k drone aerial landscape no music",
        )
    private val QUERY_VARIATION_SUFFIXES =
        listOf(
            "real footage",
            "no talking",
            "no music",
            "cinematic",
            "documentary",
            "timelapse",
        )

    private fun buildSafeFallbackQueries(baseQuery: String): List<String> {
        val normalizedBaseQuery = baseQuery.trim()
        if (normalizedBaseQuery.isBlank()) {
            return SAFE_FALLBACK_QUERIES
        }

        return listOf(
            normalizedBaseQuery,
            "$normalizedBaseQuery documentary 4k",
            "$normalizedBaseQuery no talking 4k",
        ) + SAFE_FALLBACK_QUERIES
    }

    private val AERIAL_QUERY_REGEX =
        Regex(
            "(aerial|drone|flyover|flythrough|fpv|bird's eye)",
            RegexOption.IGNORE_CASE,
        )
}
